name: Test Reusable Terraform Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  id-token: write
  pull-requests: write
  security-events: write

jobs:
  test-terraform-workflow:
    name: Test Terraform Workflow
    uses: rv2811/secret_expiry/.github/workflows/main.yml@main
    with:
      branch: main
      environment: prod
      infra: my-infra
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
